### ISSUE TITLE
Document Triggers Save Functionality Even When Unmodified

### ISSUE THREAD

**Issue by Slacky300** [Slacky300/REAL_TIME_EDIFY#15]
**Description**: Currently, the document save functionality is being triggered even when there are no changes made to the document. This can lead to unnecessary save operations, potentially causing performance issues and confusion for users who may think their document has been modified when it hasn’t.

![bug](https://github.com/user-attachments/assets/8fa5abd7-4a91-4583-a11b-cae566cdc5a3)

**Tasks**:

- Investigate the conditions under which the save functionality is being triggered.
- Implement a change detection mechanism that only triggers the save operation when the document has been modified.
- Test the functionality to ensure that the save operation is only triggered when actual changes are made to the document.

**Expected Outcome**: The document save functionality should only be triggered when there are actual modifications made to the document, reducing unnecessary save operations and improving overall performance.

**Comment by a-mais** [comment]
I will fix this

**Comment by Slacky300** [comment]
Okay, @a-mais assigning you this issue.

> I will fix this

**Comment by a-mais** [comment]
@Slacky300 I identified the following useEffect function, it saves the document and displays it every 70 seconds, we can keep this but if you want I can change it so that it does not display and continues saving or just leave manual saving
```
useEffect(() => {
    if (quill == null) return;

    const interval = setInterval(() => {
        toast.info('Saving document...');
        socket.emit("save-doc", { docId: currentDoc?._id, data: quill?.getContents() }, (error) => {
            if (error) {
                console.error(error);
            }
        });
    }, 70000);

    return () => {
        clearInterval(interval);
    };
}, [quill]);
```

**Comment by Slacky300** [comment]
@a-mais can you modify it such that it only triggers the save functionality after the document has been modified after the changes, you can implement a debouncing approach here

**Comment by a-mais** [comment]
> @a-mais can you modify it such that it only triggers the save functionality after the document has been modified after the changes, you can implement a debouncing approach here

Okay, I'll do it.

**Comment by a-mais** [comment]
> @a-mais can you modify it such that it only triggers the save functionality after the document has been modified after the changes, you can implement a debouncing approach here

Okay, I'll do it.

**Comment by a-mais** [comment]
#18
