### ISSUE TITLE
Implement Dark Mode for the Application

### ISSUE THREAD

**Issue by Slacky300** [Slacky300/REAL_TIME_EDIFY#16]
**Description**: Add a dark mode option to the RealTimeEdify application. This feature should allow users to toggle between light and dark themes for a better user experience, especially in low-light environments.

**Tasks**:

- Create a toggle switch in the UI to enable/disable dark mode.
- Update the CSS to support a dark theme across all pages.
- Ensure that text and icons are readable and accessible in dark mode.
- Store the user's theme preference in local storage so it persists across sessions.

**Expected Outcome**: A dark mode feature that users can easily switch on and off, providing a comfortable viewing experience in different lighting conditions.

**Comment by a-mais** [comment]
hi, can I do this issue? If yes, how can I go about submitting it?

**Comment by Slacky300** [comment]
> hi, can I do this issue? If yes, how can I go about submitting it?

@a-mais , yes sure you can go ahead, `fork` this repo, then create a branch named `isssue-16` push your changes to that branch and then create a pull request to this repo's `master` branch.

**Comment by a-mais** [comment]
> > hi, can I do this issue? If yes, how can I go about submitting it?
> 
> @a-mais , yes sure you can go ahead, `fork` this repo, then create a branch named `isssue-16` push your changes to that branch and then create a pull request to this repo's `master` branch.

@Slacky300 ok, I'm already implementing it, maybe I'll send it today
I added the button to the navbar so that it is present on all pages just like the navbar already is

![image](https://github.com/user-attachments/assets/17f0eaa1-53c9-46be-8911-7cd085008b13)
![image](https://github.com/user-attachments/assets/f3118d72-9708-41e3-a7ea-726c630d0921)
![image](https://github.com/user-attachments/assets/7ce01663-dc14-4a87-bc3f-321af1169a71)

**Comment by Slacky300** [comment]
@a-mais great work, but can you please create a `pull request` for the changes you made showcasing the dark/light mode in action for all the pages, you can include `images` or a `small video` walkthrough, then accordingly I can merge it with the master branch.

**Comment by a-mais** [comment]
#17 @Slacky300
